name: Tests workflow

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: true

    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Execute Tests
        run: yarn test:ci